### ISSUE TITLE
Question about download tool

### ISSUE THREAD

**Issue by Marcelo5444** [imatge-upc/videolabeler#1]
Hi guys,  what tool did you use to download the youtube videos, I am using a common one but the images and the labels missmatch

**Comment by bluque** [comment]
The only option I can think of is jDownloader, but it was a very long time ago so I'm not really sure

**Comment by Marcelo5444** [comment]
Hi, I solved the problem.What it happends is that the 1st video is at 60 FPS but some downloaders dont have that option and then, the input and the labels missmatch.Solution:Use a 60 FPS downloader
